import re
from fpdf import FPDF

class PDFReportGenerator(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, "DeepResearch AI - Sourced Research Report", border=0, align="R")
        self.ln(12)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}} | Generated by DeepResearch AI", border=0, align="C")

def sanitize_text(text: str) -> str:
    """Sanitize text for standard FPDF Latin-1 font compatibility."""
    if not text:
        return ""
    replacements = {
        '—': '-', '–': '-', '“': '"', '”': '"', '‘': "'", '’': "'",
        '•': '*', '…': '...', '™': '(TM)', '®': '(R)', '©': '(C)'
    }
    for orig, rep in replacements.items():
        text = text.replace(orig, rep)
    return text.encode('latin-1', 'replace').decode('latin-1')

def generate_pdf_report(title: str, topic: str, depth: str, created_at_str: str, content_markdown: str, sources: list) -> bytes:
    """Generate a clean, professional PDF document from a research report."""
    pdf = PDFReportGenerator()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Title Banner
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(15, 23, 42)
    pdf.set_x(10)
    pdf.multi_cell(0, 10, sanitize_text(title))
    pdf.ln(4)

    # Metadata Bar
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(71, 85, 105)
    meta_info = f"Topic: {topic} | Depth: {depth.capitalize()} | Date: {created_at_str} | Sources: {len(sources)}"
    pdf.set_x(10)
    pdf.cell(0, 6, sanitize_text(meta_info), ln=True)
    
    y = pdf.get_y() + 4
    pdf.set_draw_color(226, 232, 240)
    pdf.line(10, y, 200, y)
    pdf.set_y(y + 4)
    pdf.set_x(10)

    lines = content_markdown.split("\n")
    
    for line in lines:
        stripped = line.strip()
        if not stripped:
            pdf.ln(2)
            continue
        
        clean_line = re.sub(r'[*_`#]', '', stripped)
        clean_line = re.sub(r'\[([^\]]+)\]\([^)]+\)', r'\1', clean_line)
        clean_line = sanitize_text(clean_line).strip()

        if not clean_line:
            continue

        pdf.set_x(10) # Ensure cursor is at left margin before each line

        if stripped.startswith("# "):
            pdf.ln(4)
            pdf.set_font("Helvetica", "B", 15)
            pdf.set_text_color(30, 41, 59)
            pdf.multi_cell(0, 8, clean_line)
            pdf.ln(2)
        elif stripped.startswith("## "):
            pdf.ln(3)
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(51, 65, 85)
            pdf.multi_cell(0, 7, clean_line)
            pdf.ln(1)
        elif stripped.startswith("### "):
            pdf.ln(2)
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(71, 85, 105)
            pdf.multi_cell(0, 6, clean_line)
        elif stripped.startswith("> "):
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(100, 116, 139)
            pdf.multi_cell(0, 5, clean_line)
        elif stripped.startswith("* ") or stripped.startswith("- "):
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(30, 41, 59)
            pdf.multi_cell(0, 5, f"* {clean_line}")
        else:
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(30, 41, 59)
            pdf.multi_cell(0, 5, clean_line)

    return bytes(pdf.output())
